on:
  push:
    branches:
      - main
    paths:
      - 'syncvar/scribblings/**'
      - '.github/workflows/docs.yml'
jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.9
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: 'stable'
    - name: install lib package
      run: raco pkg install --name syncvar-lib --batch --auto ./syncvar-lib
    - name: install base package
      run: raco pkg install --name syncvar --batch --auto ./syncvar
    - name: build docs
      run: scribble +m --redirect-main http://pkg-build.racket-lang.org/doc/ --htmls --dest ./docs ./syncvar/scribblings/syncvar.scrbl
    - name: push to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        folder: docs/syncvar
        branch: gh-pages
