on:
  push:
  pull_request:
  schedule:
  - cron: "17 16 * * THU"
jobs:
  test:
    strategy:
      matrix:
        racket-variant: ["BC", "CS"]
        racket-version: ["8.5", "8.6", "pre-release", "stable", "current"]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.9
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: install lib package
      run: raco pkg install --name syncvar-lib --batch --auto ./syncvar-lib
    - name: install base package
      run: raco pkg install --name syncvar --batch --auto ./syncvar
    - name: check declared dependencies
      run: raco setup --check-pkg-deps --unused-pkg-deps --pkgs syncvar syncvar-lib
    - name: run tests
      run: raco test --drdr --package syncvar syncvar-lib
